### ISSUE TITLE
A-Frame examples are broken with the extension

### ISSUE THREAD

**Issue by fernandojsg** [MozillaReality/WebXR-emulator-extension#100]
eg: Go to https://aframe.io/aframe/examples/boilerplate/3d-model/
The console shows:
```
TypeError: navigator.xr.requestDevice is not a function
```

both on Chrome and on Firefox on Mac with the extension installed

**Comment by Galadirith** [comment]
Not to reopen this issue, but for anyone finding themselves here, A-Frame apps using master builds since https://github.com/aframevr/aframe/commit/fb322bc51e38272b3afa927a293c5844bdc3782c work with the current release (https://github.com/MozillaReality/WebXR-emulator-extension/commit/a12a92a2140359c2676716ffb7cb5ede6ce650e9) of `WebXR-emulator-extension`. In particular it works when used with build [`aframe-master.min.js@fb322bc`](https://cdn.jsdelivr.net/gh/aframevr/aframe@fb322bc51e38272b3afa927a293c5844bdc3782c/dist/aframe-master.min.js) for example https://glitch.com/~as1-position-webxr

**Comment by felipenmoura** [comment]
> Not to reopen this issue, but for anyone finding themselves here, A-Frame apps using master builds since [aframevr/aframe@fb322bc](https://github.com/aframevr/aframe/commit/fb322bc51e38272b3afa927a293c5844bdc3782c) work with the current release ([a12a92a](https://github.com/MozillaReality/WebXR-emulator-extension/commit/a12a92a2140359c2676716ffb7cb5ede6ce650e9)) of `WebXR-emulator-extension`. In particular it works when used with build [`aframe-master.min.js@fb322bc`](https://cdn.jsdelivr.net/gh/aframevr/aframe@fb322bc51e38272b3afa927a293c5844bdc3782c/dist/aframe-master.min.js) for example https://glitch.com/~as1-position-webxr

THANK YOU.
Finally a comment that helps us fixing the problem.
