### ISSUE TITLE
Cardboard button support

### ISSUE THREAD

**Issue by takahirox** [MozillaReality/WebXR-emulator-extension#113]
From https://github.com/MozillaReality/WebXR-emulator-extension/pull/111#issuecomment-539201200

Cardboard doesn't have a controller but has a button. Sounds good if we emulate.

**Comment by takahirox** [comment]
Thinking of where the button should be placed. In Headset box?

![image](https://user-images.githubusercontent.com/7637832/69267835-d1b25200-0b82-11ea-83de-506800d0fa6c.png)

**Comment by joshmarinacci** [comment]
I would create a new controller that has only a button

**Comment by takahirox** [comment]
That may sound better. I'd like to try to make.

**Comment by takahirox** [comment]
Note to self: Maybe we should use XRInputSource.targetRayMode = 'gaze'?

https://www.w3.org/TR/webxr/#xrinputsource-interface

**Comment by kylebakerio** [comment]
still looking for this.

honestly, since a cardboard 'button' is activated by just touching the screen while in VR mode, I really think just 'touching the screen' should cause the 'gaze' button to fire.

currently no way to emulate cardboard button on chrome, which is making troubleshooting attempts to get the cardboard button working hard.
