### ISSUE TITLE
Set up XRInputSource.profiles properly

### ISSUE THREAD

**Issue by mkungla** [MozillaReality/WebXR-emulator-extension#194]
When using WebXR-emulator-extension with aframe scenes profiles[n]  returns undefined. I haven't identified that this is a bug with aframe!? Or is it aframevr/aframe#4373

**Comment by takahirox** [comment]
Hi, thanks for the report. We the extension don't implement `XRInputSource.profiles` properly yet.

**Comment by takahirox** [comment]
Another problem caused by undefined `XRInputSource.profiles` seems that Three.js `XRControllerFactory` always loads Oculus Go controllers regardless of the emulated device type. (Thanks for the report @mrdoob)

[This input profile viewer](https://immersive-web.github.io/webxr-input-profiles/packages/viewer/dist/index.html) would help to know the right configuration.
