### ISSUE TITLE
How to translate?

### ISSUE THREAD

**Issue by paulrouget** [MozillaReality/WebXR-emulator-extension#231]
I can rotate the headset and controller, but I really have no idea how to translate. I see issues and code for translating the headset and the controller, but I don't understand how to do that. The gif in the README show that there is a mode for translation, but how do I turn that mode on?

**Comment by paulrouget** [comment]
According to the code, clicking should cycle between 3 modes, disabled, translate and rotate. In my case it cycles between disabled and rotate.

**Comment by paulrouget** [comment]
Both Chrome and Firefox.

**Comment by joshmarinacci** [comment]
I ran into this as well. Translate is disabled if you have a 3dof (three degree of freedom) headset selected. I think the Oculus Go is the default headset, which is 3dof. Perhaps it would make more sense to have multiple radio buttons and you can chose the mode, with the translate one visibly disabled if 3dof is selected.

**Comment by takahirox** [comment]
Hi @paulrouget, thanks for reporting the issue. As @joshmarinacci explained, it is intentional if you choose 3dof device (the default is Oculus Go 3dof device). If you choose 6dof device like Oculus Quest from the device list in the devtool panel, I think you can also translate.

And agreed with @joshmarinacci 's suggestion. It would be good to visible what capability the selected device has to users. Once @paulrouget confirms he can rotate with 6dof device, I want to change the title like "Visible device capability" or create a new issue.

**Comment by paulrouget** [comment]
I'm trying all the other devices, and I still don't see how this is suppose to work.

**Comment by takahirox** [comment]
What version of the extension do you use? Please ensure that you choose Oculus Quest from the device list and then

If v0.3.0, click the device in devtool panel. You can change the control mode, rorate, translate, or disable.

If v0.2.1 or older, you can enable the control by clicking gizmo checkbox. And then click rotate/translate button at bottom of the devtool panel, you can change the control mode rotate or translate.

**Comment by paulrouget** [comment]
Ok - I didn't realize the rotate button could be toggled to translate. Thanks.

**Comment by takahirox** [comment]
Sorry for bad UI design. I would recommend to use the newest version v0.3.0 (Released for Firefox at add-on store, and will be released soon for Chrome at web-store). It has more intuitive control UI, you can change the control  mode by clicking the devices as I mentioned.
